name: release a new topology builder docker image

on:
  pull_request:
  workflow_dispatch:

env:
  ECR_ACCOUNT_ID: "910202568813"
  ECR_PROD_REGISTRY: 910202568813.dkr.ecr.us-east-2.amazonaws.com/kafka-topology-builder
  ECR_PROD_ROLE: arn:aws:iam::910202568813:role/ecr-github-kong-julie

jobs:
  release-details:
    name: Make Release Date
    runs-on: ubuntu-latest
    outputs:
      release_date: ${{ steps.date.outputs.release_date }}
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=release_date::$(date +'%Y-%m-%d-%H-%M')"

  release-image:
    name: Release Image
    runs-on: ubuntu-latest
    needs: release-details
    if: ${{needs.release-details.result == 'success'}}
    environment: prod
    permissions:
        contents: read
        id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up the JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: copy fat jar
        run: cp ./target/julie-ops.jar release/docker

      - name: copy runner file
        run: cp ./src/main/scripts/julie-ops-cli.sh release/docker

      - name: list files (release dir)
        run: ls -l
        working-directory: release/docker

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: release/docker
          file: release/docker/Dockerfile
          push: false
          tags: ${{ env.ECR_PROD_REGISTRY }}:${{ needs.release-details.outputs.release_date }}
